[package]
name = "rustical"
version = "0.1.0"
authors = ["Arthur Henrique <arthur393@gmail.com>"]
edition = "2018"
description = "⚡️ Lightning-fast and minimal calendar command line. It's similar to `cal` but simpler and uglier. Written in Rust 🦀"
readme = "README.md"
repository = "https://github.com/arthurhenrique/rustical"
license-file = "LICENSE"
keywords = ["calendar", "cal"]
categories = ["command-line-utilities"]

[dependencies]
